#!/bin/bash
image_name=${PWD##*/}
tag=$(git describe)

if [[ ! "$(git update-index --refresh; git diff-index --quiet HEAD --)" == "" ]]; then
  echo "Uncommitted local changes."
  exit
fi

if [[ "$(git ls-remote -q origin refs/tags/$tag)" =~ "$tag" ]]; then
  echo "Tag already exists on origin."
  exit
fi

docker build --no-cache --tag thejonanshow/$image_name:$tag .
container=$(docker run -d thejonanshow/$image_name:$tag /bin/true)
docker export $container | docker import - thejonanshow/$image_name:$tag
docker container rm $container
docker push thejonanshow/$image_name:$tag
